"""Initial

Revision ID: bddda9eb0f0b
Revises: 
Create Date: 2025-06-11 10:04:17.105731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddda9eb0f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos_detectados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho_imagem', sa.String(), nullable=False),
    sa.Column('placa_original', sa.String(), nullable=True),
    sa.Column('placa_corrigida', sa.String(), nullable=True),
    sa.Column('placa_valida', sa.Boolean(), nullable=True),
    sa.Column('xmin', sa.Integer(), nullable=True),
    sa.Column('xmax', sa.Integer(), nullable=True),
    sa.Column('ymin', sa.Integer(), nullable=True),
    sa.Column('ymax', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caminho_imagem', 'placa_original', name='uix_imagem_placa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos_detectados')
    # ### end Alembic commands ###
